const handleProfileGet = (req, res, db) => {
	const { id } = req.params;

	db.select("*")
		.from("users")
		.where({ id })
		.then((user) => {
			if (user.length) {
				res.json(user[0]);
			} else {
				res.status(400).json("not found");
			}
		});
	// cannot use .catch() here to catch any errors because the .then() returns an empty array even when no user is present. It doesn't actually throw any error.
};

module.exports = {
  handleProfileGet: handleProfileGet,
};
